server:
  host: 0.0.0.0
  port: :9088
db:
  name: db_common
  addr: 127.0.0.1:3306
  username: root
  password: mustang
  gorm:
    logMode: 0
    maxOpenConn: 100
    maxIdleConn: 10
    singularTable: 1
mq:
  mq_addr: "amqp://guest:guest@localhost:5672/"
  queue_name: "msgQueueWithPersist"
  producernt: 5
  consumercnt: 20
log:
  level: debug
  maxsize: 1
  maxage: 30
  maxbackups: 10
  localtime: 1
  compress: 1
  fileName: golang-common-base.log
api:
  version: /api/v1
jwt:
  secret: vz5(#pfnf+#p5ok&d2yrqd#)k0jz!#tb*$=^c5nl0(z+0=p5!9
email:
  eim:
    server: partner.outlook.cn
    sender: eim@xxx.com
    password: 123456
    port: 587
    security: true
  support:
    server: partner.outlook.cn
    sender: support@xxx.com
    password: 123456
    port: 587
    security: true